name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Restore
        run: dotnet restore src/ProjControleFinanceiroApi/ProjControleFinanceiroApi.csproj
        
      - name: Build
        run: dotnet build ./src/ProjControleFinanceiroApi/ProjControleFinanceiroApi.csproj --no-restore
        
      - name: Publish
        run: dotnet publish ./src/ProjControleFinanceiroApi/ProjControleFinanceiroApi.csproj -o publish/Api --no-build
